FROM node:22-alpine AS build

WORKDIR /app

RUN npm install -g pnpm

COPY package.json pnpm-lock.yaml turbo.json pnpm-workspace.yaml ./
COPY apps/frontend/package.json ./apps/frontend/

RUN pnpm install --frozen-lockfile 

COPY apps/frontend ./apps/frontend

WORKDIR /app/apps/frontend
RUN pnpm build

