name: WebSocket-Deployment

on:
  push: 
    branches: 
      - main
    paths: 
      - 'apps/ws/**'
      - 'packages/services/**'
      - '.github/workflows/deploy-ws.yml'
      - 'docker/Dockerfile.ws'

jobs: 
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./docker/Dockerfile.ws
          push: true
          tags: |
            ikrambagban/exness-ws:${{ github.sha }}
            ikrambagban/exness-ws:latest

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USERNAME }}
          key: ${{ secrets.VM_SSH_KEY }}
          script: |
            docker pull ikrambagban/exness-ws:${{ github.sha }}
            docker network inspect exness-network || docker network create exness-network

            docker stop exness-ws || true
            docker rm exness-ws || true
            docker run -d \
              --name exness-ws \
              --restart always \
              --network exness-network \
              -p 8080:8080 \
              -e REDIS_URL="${{ secrets.REDIS_URL }}" \
              -e NODE_ENV="production" \
              ikrambagban/exness-ws:${{ github.sha }}
